### ISSUE TITLE
README

### ISSUE THREAD

**Issue by sidhu1012** [Dacience/DataScientist#20]
Make proper README

**Comment by yashgautam9274** [comment]
I want to do this work please assign me

**Comment by sidhu1012** [comment]
> I want to do this work please assign me

There is no need to assign specifically, comment I'm working and get started.

**Comment by vybhav72954** [comment]
Is this still open?

**Comment by sidhu1012** [comment]
> Is this still open?
> 

I don't think so. Please check issues to find a relevant issue!
