### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by sidhu1012** [Dacience/DataScientist#33]
Make a logo for this library and add it to README

**Comment by yashgautam9274** [comment]
I will do this assign me

**Comment by sidhu1012** [comment]
> I will do this assign me

There is no need to assign specifically, comment I'm working and get started.

**Comment by yashgautam9274** [comment]
![logo_DataScientist](https://user-images.githubusercontent.com/72320108/100760772-20422f80-3418-11eb-9d70-9ecd082e73fe.png)
is this logo is good

**Comment by sidhu1012** [comment]
> ![logo_DataScientist](https://user-images.githubusercontent.com/72320108/100760772-20422f80-3418-11eb-9d70-9ecd082e73fe.png)
> is this logo is good

Yes , do you have rights over it?

**Comment by yashgautam9274** [comment]
yes

**Comment by yashgautam9274** [comment]
can i add this logo in readme file

**Comment by sidhu1012** [comment]
> can i add this logo in readme file

Yes
