### ISSUE TITLE
Make sub-module Data Analysis 

### ISSUE THREAD

**Issue by sidhu1012** [Dacience/DataScientist#37]
Make a sub module Data analysis which takes input inform of array or data frame and returns relation between every column, missing values etc , with relevant plots.

**Comment by kritikaparmar-programmer** [comment]
Hey, @sidhu1012 Do we have to do something like seaborn pairplots??

**Comment by sidhu1012** [comment]
> Hey, @sidhu1012 Do we have to do something like seaborn pairplots??

Yes all relevant plots using seaborn and matplotlib .

Dataframe of missing values, correlation between data, varience, standard deviation bwteen columns and many more features relevant to Data Analysis.

**Comment by sidhu1012** [comment]
Dessign should be of a main(public) function, which can call other helper(private) functions if necessary.

**Comment by kritikaparmar-programmer** [comment]
Ok I want to work on this

**Comment by sidhu1012** [comment]
You got it!

**Comment by sidhu1012** [comment]
> Ok I want to work on this 

You got it!

**Comment by sidhu1012** [comment]
It should be Exploratory Data Analysis #29

**Comment by khushibalyan220101** [comment]
I would like to contribute to this issue

**Comment by sidhu1012** [comment]
> I would like to contribute to this issue

@kritikaparmar-programmer is working on it I think.

**Comment by parva-jain** [comment]
What's the status of this issue? If no one is working on it then I can try my hands on it.

**Comment by sidhu1012** [comment]
> What's the status of this issue? If no one is working on it then I can try my hands on it.

@kritikaparmar-programmer are you still working?

**Comment by kritikaparmar-programmer** [comment]
Yes I'll make pr within two days @sidhu1012
