### ISSUE TITLE
Make Contributing.md

### ISSUE THREAD

**Issue by sidhu1012** [Dacience/DataScientist#38]
Make a file for getting newcomers get started for this project.

**Comment by Pranav016** [comment]
I would like to work on this issue.

**Comment by sidhu1012** [comment]
@Pranav016 Surely!!

**Comment by Kerveyfelix** [comment]
Can I work on this issue?

**Comment by sidhu1012** [comment]
> Can I work on this issue?

This issue is already taken and is almost done too! Please check issues to find any other relevant issue.
