### ISSUE TITLE
Make Code_of_conduct.md

### ISSUE THREAD

**Issue by sidhu1012** [Dacience/DataScientist#39]
Make a `.md` file for guidelines , standards, do's, dont's etc

**Comment by Pranav016** [comment]
I would like to work on this issue as a part of NJACK.

**Comment by sidhu1012** [comment]
@Pranav016 Surely!

**Comment by yashgautam9274** [comment]
i want to work on this issue

**Comment by sidhu1012** [comment]
> i want to work on this issue

There are already 2 PR's for this issue . Please look for other issues.
