### ISSUE TITLE
update setup.py

### ISSUE THREAD

**Issue by anishkabhatia** [Dacience/DataScientist#59]
on running the pip install -e . command, 
"UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 888: character maps to <undefined>" this error comes up.

Fixing this issue by changing the setup.py file

Please assign this to me. Thank you

**Comment by anishkabhatia** [comment]
@sidhu1012 Can I start working on this?

**Comment by sidhu1012** [comment]
> @sidhu1012 Can I start working on this?
> 

I haven't debugged it yet. So it's up to you.
