### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by sidhu1012** [Dacience/DataScientist#63]
code of conduct and contributing.md link not working in readme.

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by sidhu1012** [comment]
> I want to work on this issue

You got it!

**Comment by yashgautam9274** [comment]
@sidhu1012  it is mistake of person who made these file.

**Comment by sidhu1012** [comment]
> @sidhu1012  it is mistake of person who made these file. 
> 

Actually Code of conduct and contributing files were made after readme so it's now actually a mistake.
