### ISSUE TITLE
Set Up discussion feature for great conversion

### ISSUE THREAD

**Issue by Vishal-raj-1** [Dacience/DataScientist#65]
@sidhu1012 , Did you see new feature on github ? We can set discussion on this repo. So what you have to do is just click this block in setting section of your repo. It's Amazing I guess. Have a try.

![discussion](https://user-images.githubusercontent.com/59874304/101589985-8c6ff500-3a0f-11eb-8756-48b53dfe1adf.JPG)

**Comment by sidhu1012** [comment]
@Vishal-raj-1 Yes I saw it earlier this morning.

**Comment by Vishal-raj-1** [comment]
@sidhu1012 I have seen this in Github Universe event. I think you should also try that mind blowing event. 

Thanks & Regards
Vishal
